### PR TITLE
Small fixes for FormTimedMessage,FormDialog,FormFirst,FormAllSetting

### LINKED ISSUE #953: Profile messages don't fit
Profile warning message texts do not fit boxes.

Image

Image

### PR DESCRIPTION
**Pull request by richardklasens**
Fixes multiple issues
Closes #953 #931 #908 #909

### CODE REVIEW

File: SourceCode/GPS/Forms/FormTimedMessage.cs
Comment (FantasyTeddy) [inline SourceCode/GPS/Forms/FormTimedMessage.cs:1]: Just as a heads-up: this will probably cause a conflict with #969 when we merge the release back into develop.

File: SourceCode/GPS/Forms/Settings/FormAllSettings.cs [hunk 1]
```diff
@@ -94,9 +94,9 @@ private void LoadLabels()
             label126.Text = Properties.Settings.Default.setTool_trailingToolToPivotLength.ToString();
             label128.Text = Properties.Settings.Default.setVehicle_hitchLength.ToString();
             label130.Text = Properties.Settings.Default.setVehicle_hydraulicLiftLookAhead.ToString();
-            label132.Text = "*****";
+            label132.Text = "N/A";
             label134.Text = Properties.Settings.Default.setVehicle_isStanleyUsed.ToString();
-            label136.Text = "*****";
+            label136.Text = "N/A";
```
Comment (FantasyTeddy) [inline SourceCode/GPS/Forms/Settings/FormAllSettings.cs:99]: Do we know what these settings should be set to? If we don't shouldn't we just remove them?

Comment (richardklasens) [reply SourceCode/GPS/Forms/Settings/FormAllSettings.cs:99]: they can be removed but then you need to do a big overhaul on the page.

File: SourceCode/GPS/Forms/FormTimedMessage.cs
Comment (richardklasens) [reply SourceCode/GPS/Forms/FormTimedMessage.cs:1]: We will see :)

File: SourceCode/GPS/Forms/Settings/FormAllSettings.cs (hunk 1 above)
Comment (FantasyTeddy) [reply SourceCode/GPS/Forms/Settings/FormAllSettings.cs:99]: Okay, so maybe something to do in develop then?
