### PR TITLE
fixed the upload and download fields without a boundary AgShare

### LINKED ISSUE #978: AgShare Selected Field not entirely visible
v6.8.0b3

Image

### PR DESCRIPTION
**Pull request by richardklasens**
this also fixes #978

### CODE REVIEW

File: SourceCode/GPS/Classes/AgShare/AgShareUploader.cs [hunk 1]
```diff
@@ -66,17 +66,22 @@ public static async Task UploadAsync(FieldSnapshot snapshot, AgShareClient clien
...
             try
             {
-                if (snapshot.Boundaries == null || snapshot.Boundaries.Count == 0)
-                    return;
-
-                List<CoordinateDto> outer = ConvertBoundary(snapshot.Boundaries[0], snapshot.Converter);
-                if (outer == null || outer.Count < 3) return;
+                // Allow upload even without boundary - boundary is optional
+                List<CoordinateDto> outer = new List<CoordinateDto>();
+                if (snapshot.Boundaries != null && snapshot.Boundaries.Count > 0)
```
Comment (FantasyTeddy) [inline SourceCode/GPS/Classes/AgShare/AgShareUploader.cs:73]: It took me quite some time to figure out why the `Boundaries` are being checked twice for `null`. Maybe consider doing one big `if (snapshot.Boundaries != null)` around everything related to the boundaries.

Additionally, I would consider using `FirstOrDefault` to get the first item, in order to make the intention more clear.

File: SourceCode/GPS/Classes/AgShare/AgShareUploader.cs [hunk 2]
```diff
@@ -66,17 +66,22 @@ public static async Task UploadAsync(FieldSnapshot snapshot, AgShareClient clien
...
+                    if (outer == null) outer = new List<CoordinateDto>();
+                }
 
                 List<List<CoordinateDto>> holes = new List<List<CoordinateDto>>();
-                for (int i = 1; i < snapshot.Boundaries.Count; i++)
+                if (snapshot.Boundaries != null)
                 {
-                    List<CoordinateDto> hole = ConvertBoundary(snapshot.Boundaries[i], snapshot.Converter);
-                    if (hole.Count >= 4) holes.Add(hole);
+                    for (int i = 1; i < snapshot.Boundaries.Count; i++)
```
Comment (FantasyTeddy) [inline SourceCode/GPS/Classes/AgShare/AgShareUploader.cs]: Maybe consider using a `foreach` loop instead. (and use `Skip(1)` to exclude the first one)

File: SourceCode/GPS/Classes/AgShare/AgShareUploader.cs [hunk 3]
```diff
@@ -66,17 +66,26 @@ public static async Task UploadAsync(FieldSnapshot snapshot, AgShareClient clien
...
-
-                List<CoordinateDto> outer = ConvertBoundary(snapshot.Boundaries[0], snapshot.Converter);
-                if (outer == null || outer.Count < 3) return;
-
+                // Allow upload even without boundary - boundary is optional
+                List<CoordinateDto> outer = new List<CoordinateDto>();
                 List<List<CoordinateDto>> holes = new List<List<CoordinateDto>>();
-                for (int i = 1; i < snapshot.Boundaries.Count; i++)
+
+                if (snapshot.Boundaries != null && snapshot.Boundaries.Count > 0)
```
Comment (FantasyTeddy) [inline SourceCode/GPS/Classes/AgShare/AgShareUploader.cs:73]: You could also remove the `Count` check, because you are already handling the case of an empty list with `FirstOrDefault`.
