### PR TITLE
fixes 

### LINKED ISSUE #640: No icon menu option Charts -> Roll Check
Image

No icon menu option Charts -> Roll Check

### LINKED ISSUE #649: Steermode Auto Scaling Mode
the Auto-scaling mode in the Steergraph should be active when opening the form

### PR DESCRIPTION
**Pull request by richardklasens**
Resolves #640 
Resolves #649

### CODE REVIEW

File: SourceCode/GPS/Forms/Settings/FormGraphSteer.cs [hunk 1]
```diff
@@ -75,12 +75,13 @@ private void FormSteerGraph_Load(object sender, EventArgs e)
...
+            unoChart.ChartAreas[0].AxisY.Maximum = Double.NaN;
+            unoChart.ChartAreas[0].AxisY.Minimum = Double.NaN;
+            unoChart.ChartAreas[0].RecalculateAxesScale();
             unoChart.ResetAutoValues();
-
-            lblMax.Text = ((int)(unoChart.ChartAreas[0].AxisY.Maximum * 0.01)).ToString();
-            lblMin.Text = ((int)(unoChart.ChartAreas[0].AxisY.Minimum * 0.01)).ToString();
+            lblMax.Text = "Auto";
+            lblMin.Text = "";
+            isAuto = true;
```
Comment (FantasyTeddy) [inline SourceCode/GPS/Forms/Settings/FormGraphSteer.cs:84]: Maybe we could extract this code and the code in `btnGainAuto_Click` into a new method and call that instead?
