### PR TITLE
Fix Worked Tracks Skipper

### LINKED ISSUE #936: Skip worked pass U turn mode not working
v6.8.0b3

https://github.com/user-attachments/assets/baefb2e4-dc51-474d-a168-08f026634e27

### PR DESCRIPTION
**Pull request by richardklasens**
Fixes #936

### CODE REVIEW

File: SourceCode/GPS/Classes/CYouTurn.cs [hunk 1]
```diff
@@ -182,9 +193,20 @@ public bool BuildCurveDubinsYouTurn()
...
-            //if mode is skip workedTracks -> next Track is an already worked track, find the next not worked track and use it.
+            //if mode is skip workedTracks -> mark current track as worked if sections were on, then find next
             if (skipMode == SkipMode.IgnoreWorkedTracks)
+            {
+                // Mark the current track as worked only if sections were actually on
+                if (mf.trk.idx >= 0 && mf.trk.idx < mf.trk.gArr.Count)
+                {
+                    if (mf.autoBtnState == btnStates.Auto || mf.manualBtnState == btnStates.On)
+                    {
+                        mf.trk.gArr[mf.trk.idx].workedTracks.Add(mf.ABLine.howManyPathsAway);
```
Comment (J005t67) [inline SourceCode/GPS/Classes/CYouTurn.cs:204]: Most  of the added code is already duplciate code now. (Except the 'howManyPathsAway). Why not implement the new code only once, (for example in the function GetNextNotWorkedTrack.)

**Review by J005t67 — CHANGES_REQUESTED** [review]

File: SourceCode/GPS/Classes/CYouTurn.cs (hunk 1 above)
Comment (richardklasens) [reply SourceCode/GPS/Classes/CYouTurn.cs:204]: I know but I leave it as is.. I won’t harm that much anymore.
