### PR TITLE
Fix AgShare Boundary

### LINKED ISSUE #959: AgShare upload download issue with boundary
When downloading an uploaded field and use headland designer to create a headland the headland gets a strange behavior in polygon design. After import the boundary list should walk over FixFenceLine to get equal spacing between points.

Image
Image

### PR DESCRIPTION
**Pull request by richardklasens**
Put Boundary downloaded from AgShare into BoundaryList to make point spacing heading and winding correct

fixes #959

### CODE REVIEW

File: SourceCode/GPS/Classes/AgShare/AgShareDownloader.cs [hunk 1]
```diff
@@ -159,19 +159,45 @@ private static void WriteBoundaryTxt(string fieldDir, List<List<LocalPoint>> bou
...
-                lines.Add(ring.Count.ToString());
 
-                var enriched = BoundaryHelper.WithHeadings(ring);
+                // ---- Normalize ring using CBoundaryList ----
+                var bnd = new CBoundaryList();
 
-                foreach (var pt in enriched)
+                // Ensure fenceLine exists and is empty
+                if (bnd.fenceLine == null)
+                    bnd.fenceLine = new List<vec3>();
```
Comment (J005t67) [inline SourceCode/GPS/Classes/AgShare/AgShareDownloader.cs:171]: Please use {} for both if and else branch

File: SourceCode/GPS/Classes/AgShare/AgShareDownloader.cs [hunk 2]
```diff
@@ -159,19 +159,45 @@ private static void WriteBoundaryTxt(string fieldDir, List<List<LocalPoint>> bou
...
+                }
+
+                // First calculate area / winding (FixFenceLine spacing depends on area; winding may be reversed here)
+                bnd.CalculateFenceArea(i);
+
+                // Then fix spacing and recalc headings (also populates fenceLineEar if used elsewhere)
+                bnd.FixFenceLine(i);
+
+                // Use the fixed/normalized fenceLine for output
+                int fixedCount = (bnd.fenceLine != null) ? bnd.fenceLine.Count : 0;
```
Comment (J005t67) [inline SourceCode/GPS/Classes/AgShare/AgShareDownloader.cs]: Line 196 already does a null check on bnd.fenceLine. I don't think we need it here.
